export const eventData = [
    {
        title: "Halloween Party",
        description: "Halloween party, yeah! It will be fun!",
        eventDate: '2024, 9, 31',
        organizer: "Pumpkin Jack",
    },
    {
        title: "Bakery China",
        description: "World's leading exhibition of baking products and services.",
        eventDate: '2024, 6, 2',
        organizer: "Sam Lee",
    },
    {
        title: "Palm Beach Home Design and Remodeling Show",
        description: "A Wealth of Ideas Under One Roof.",
        eventDate: '2024, 7, 17',
        organizer: "Home Show Management Corp.",
    },
    {
        title: "Tri-County Home & Garden Show",
        description: "No matter what home style you are looking to create, tiny or traditional, The Home & Garden Show & Tiny House Expo has the licensed contractors and vendors to make your vision for your home and garden come true!.",
        eventDate: '2024, 5, 19',
        organizer: "Tri-County Home & Garden Show.",
    },
    {
        title: "Tarrant County State of the Market",
        description: "Discover the reasons to attend the Tarrant County Commercial Real Estate event and learn about Fort Worth's growth factors, upcoming developments, developer influence, business opportunities, investment trends, and emerging sectors.",
        eventDate: '2024, 8, 21',
        organizer: "Bisnow",
    },
    {
        title: "PEGS Boston Conference & Expo",
        description: "The Essential Protein & Antibody Engineering Summit!.",
        eventDate: '2024, 9, 4',
        organizer: "Cambridge Innovation Institute",
    },
    {
        title: "Gameis Annual Meeting and Tradeshow",
        description: "The GAMEIS Annual Meeting and Tradeshow, a public event, will take place at the Savannah Convention Center.",
        eventDate: '2024, 11, 29',
        organizer: "Savannah Convention Center",
    },
    {
        title: "Healthcare Payers Transformation Assembly",
        description: "The Healthcare Providers Transformation Assembly is a groundbreaking opportunity for C-Level Healthcare Officers to connect and discuss the current trends and challenges facing the industry.",
        eventDate: '2024, 6, 13',
        organizer: "The Millenium Alliance",
    },
    {
        title: "China High-Tech Expo on Meteorological Modernization",
        description: "The most authoritative platform for meteorological industry in China.",
        eventDate: '2024, 5, 17',
        organizer: "China Meteorological Society",
    },
    {
        title: "Shanghai International Thermal Insulation Materials and Energy- saving Technology Exhibition",
        description: "The advanced thermal insulation and finishing system exhibition in Asia. An industry event focused on thermal insulation in the application field. All aspects of thermal insulation will be covered.",
        eventDate: '2024, 7, 4',
        organizer: "Shanghai Zhanye Exhibition Co Ltd",
    },
    {
        title: "International Decentralized Energy Resources Expo & Conference",
        description: "Renewable energy total solution: Contributing to carbon reduction and environmental conservation through energy integration platforms and renewable energy integrated power generation solutions, such as solar power, wind power, biomass, fuel cells, and hydrogen energy.",
        eventDate: '2024, 5, 27',
        organizer: "INFOTHE Co. Ltd.",
    },
    {
        title: "China International Disposable Paper EXPO",
        description: "Bringing together players from whole chains of tissue paper & disposable hygiene products industry.",
        eventDate: '2024, 4, 17',
        organizer: "China National Pulp and Paper Research Institute Co., Ltd.",
    },
    {
        title: "North Loup Popcorn Days Fair",
        description: "Join us for three days of fun at North Loup Popcorn Days Fair! Enjoy free popcorn, kids activities, live music, competitions, parades, and more. Don't miss the carnival, craft show, car show, and other exciting events. Come celebrate with us!.",
        eventDate: '2024, 7, 18',
        organizer: "Nebraska Association of Fair Managers",
    },
    {
        title: "Shanghai International Baby Photo Expo",
        description: " ",
        eventDate: '2024, 7, 9',
        organizer: "Shanghai International Exhibition Co Limited",
    },
    {
        title: "Contract Manufacturing & Private Label Expo",
        description: "India's only FMCG Private Label & Contract Manufacturing Supplier Sourcing Event.",
        eventDate: '2024, 4, 17',
        organizer: "CMPL EXPO-CONNECT LLP",
    },
    {
        title: "BakeryTech India",
        description: "BakeryTech India will showcase products like food processing and packaging machinery, food testing lab and equipment food sector infrastructure, grading and sorting machinery, wrapping, sealing, and lamination equipment, bar code/ink coding/POS technology, bakery, confectionary, snacks & other products.",
        eventDate: '2024, 7, 24',
        organizer: "Media Today Pvt. Ltd.",
    },
    {
        title: "Sacramento Wedding Festival",
        description: "Explore a variety of wedding vendors offering services such as bakery treats, beauty services, jewelry, and event planning. Find everything you need for your wedding day, from hair and makeup to venues and consultants.",
        eventDate: '2024, 7, 18',
        organizer: "International Wedding Festival",
    },
    {
        title: "ABC Kids Expo",
        description: "Come see new products and innovation from the top baby and kids brands.",
        eventDate: '2024, 4, 17',
        organizer: "All Baby & Child, Inc.",
    },
    {
        title: "Babies & Bumps Nashville",
        description: "Join us at Babies & Bumps Nashville 2024! Featuring local businesses, brands, and non-profits for new and soon-to-be parents. Expert-led seminars, skill-building demos, special guest Jamie Grayson, and giveaways.",
        eventDate: '2024, 6, 21',
        organizer: "Babies & Bumps",
    },
    {
        title: "Greenberg's Great Train & Toy Show",
        description: " ",
        eventDate: '2024, 6, 14',
        organizer: "Train Show",
    },
    {
        title: "CCAT Global Symposium",
        description: "The Global Symposium on Mobility Innovation annual conference will be hosted at the Morris Lawrence Building at Washtenaw Community College in Ann Arbor, MI.",
        eventDate: '2024, 4, 22',
        organizer: "University of Michigan",
    },
    {
        title: "Integrated Advisors Summit",
        description: "Experience the vibrant culture of New Orleans in 24 hours! Explore historic neighborhoods, taste delicious Creole cuisine, take a Mississippi paddle boat cruise, and join in a traditional Second Line parade.",
        eventDate: '2024, 6, 18',
        organizer: "Integrated Advisors Network",
    },
    {
        title: "The Healthcare Innovation Congress",
        description: "The only event that delivers impactful content, creates real connections, drives healthcare forward.",
        eventDate: '2024, 2, 19',
        organizer: "The Healthcare Innovation Company",
    },
    {
        title: "Vandalia Health Cardiology Symposium",
        description: "The Vandalia Health Cardiology Symposium 2024 is a free conference for Vandalia Health employees, covering topics such as transcatheter aortic valve replacement and cardiogenic shock.",
        eventDate: '2024, 7, 11',
        organizer: "Charleston Area Medical Center",
    },
    {
        title: "Protein Processing, Trafficking and Secretion Gordon Research Conference",
        description: "The Proprotein Processing, Trafficking & Secretion conference will showcase advanced research on cell biology related to secretory and endocytic pathways, including mechanisms, regulation, and new findings on proteases.",
        eventDate: '2024, 6, 19',
        organizer: "Gordon Research Conferences",
    },
    {
        title: "Advanced Automotive Battery Conference Europe",
        description: "The Advanced Automotive Battery Conference brings together battery technologists to discuss the latest trends and breakthroughs in vehicle electrification. The event in Strasbourg will play a crucial role in advancing the momentum of European nations and international automotive OEMs towards vehicle electrification and eMobility.",
        eventDate: '2024, 4, 16',
        organizer: "Cambridge Enertech",
    },
    {
        title: "APBP Conference",
        description: "The conference will provide excellent training and mobile sessions to explore Detroit's transportation history and revitalization efforts, with a focus on biking and pedestrian infrastructure.",
        eventDate: '2024, 7, 14',
        organizer: "Apbp: Expertise for Active Transportation",
    },
    {
        title: "British Vehicle Rental & Leasing Association Compliance Forum",
        description: "Our new forum brings compliance professionals together for three events, featuring expert speakers and networking opportunities. Topics include SM&CR, FOS cases, CCA Reform, and more. Annual subscriptions are available for attendance. Beware of data scams related to attendee lists.",
        eventDate: '2024, 6, 18',
        organizer: "BVRLA",
    },
]